// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace Elements10Sample
{
    public class Elements10SampleOutputs: SystemResults
    {


        /// <summary>
        /// Construct a Elements10SampleOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public Elements10SampleOutputs() : base()
        {

        }


	}
}